#!/bin/sh /etc/rc.common
# Copyright (C) 2024 Thinger.io

USE_PROCD=1
START=101
STOP=101
CONF="/etc/thinger/iotmp.cfg"

start_service() {
  procd_open_instance
  procd_set_param command "/usr/local/bin/thinger_iotmp"
  procd_append_param command -c $CONF
  procd_set_param respawn
  procd_close_instance
}
