name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/thin-remote/musl-toolchain:x86_64-linux-musl-latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        shell: bash
        run: cmake -B /build -DCMAKE_BUILD_TYPE=Release -DSTATIC=ON -DARCH=x86_64-linux-musl

      - name: Build
        run: cmake --build /build -j$(nproc)
